import "../styles/globals.css";

import Header from "./components/header/Header";
import { roboto_mono } from "../styles/fonts";

export const metadata = {
  title: "MiZaWra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto_mono.className}>
      <body className="container mx-auto">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
